# -*- coding: utf-8 -*-
"""IC_EXTRAIR VALOR DO RASTER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ob8lep4KCjjLXhzyMeUQd2obZJ-9fJKj
"""

# Preparando o ambiente no Google Drive:

#importando a biblioteca
from google.colab import drive

# Isso irá pedir sua autorização
drive.mount('/content/drive')

# Agora, seu Drive estará disponível em: /content/drive/My Drive

#Bibliotecas
! pip install geopandas
import pandas as pd
import geopandas as gpd
! pip install rasterio
import rasterio



# Ler os dados
#estacoes = pd.read_csv('/content/drive/My Drive/ESTACOES_PLUVIO.csv',sep=",")
estacoes = pd.read_csv('/content/drive/My Drive/est_pluvio.csv',sep=",")
#estacoes = pd.read_csv('/content/drive/My Drive/QUADR_TRMM.csv',sep=",")

#Criar geopandas geodataframe 
estacoes_gdf=gpd.GeoDataFrame(estacoes,geometry=gpd.points_from_xy(estacoes.Long,estacoes.LAT))

#Plotar
estacoes_gdf.plot(markersize=1.5,figsize=(10,10))

#Obter ESRI wkt
#SITE: epsg.io 
ESRI_WKT='GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]'
#ESRI_WKT='GEOGCS["SIRGAS 2000",DATUM["D_SIRGAS_2000",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]'
#Salvar shape
estacoes_gdf.to_file(filename="estacoes_precipitaca.shp", driver="ESRI Shapefile")
estacoes_gdf.crs = 'epsg:4674'
estacoes_gdf.to_file("estacoes_precipitaca.shp")

type(estacoes)



pts_82887 = estacoes_gdf.query('CODIGO==82887')
pts_82887.index

#1998
JAN_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980101-19980131.41W_9S_34W_7S (1).tif')
FEV_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980201-19980228.41W_9S_34W_7S.tif')
MAR_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980301-19980331.41W_9S_34W_7S.tif')
ABR_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980401-19980430.41W_9S_34W_7S.tif')
MAI_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980501-19980531.41W_9S_34W_7S.tif')
JUN_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980601-19980630.41W_9S_34W_7S.tif')
JUL_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980701-19980731.41W_9S_34W_7S.tif')
AGO_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980801-19980831.41W_9S_34W_7S.tif')
SET_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19980901-19980930.41W_9S_34W_7S.tif')
OUT_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19981001-19981031.41W_9S_34W_7S.tif')
NOV_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19981101-19981130.41W_9S_34W_7S.tif')
DEZ_1998 = rasterio.open('/content/drive/My Drive/TRMM/1998/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19981201-19981231.41W_9S_34W_7S.tif')

#1999
JAN_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-accumulate.TRMM_3B43_7_precipitation.19990101-19990131.41W_9S_34W_7S.tif')
FEV_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19990201-19990228.41W_9S_34W_7S.tif')
MAR_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-accumulate.TRMM_3B43_7_precipitation.19990301-19990331.41W_9S_34W_7S.tif')
ABR_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19990401-19990430.41W_9S_34W_7S.tif')
MAI_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19990501-19990531.41W_9S_34W_7S.tif')
JUN_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19990601-19990630.41W_9S_34W_7S.tif')
JUL_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19990701-19990731.41W_9S_34W_7S.tif')
AGO_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19990801-19990831.41W_9S_34W_7S.tif')
SET_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19990901-19990930.41W_9S_34W_7S.tif')
OUT_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19991001-19991031.41W_9S_34W_7S.tif')
NOV_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19991101-19991130.41W_9S_34W_7S.tif')
DEZ_1999 = rasterio.open('/content/drive/My Drive/TRMM/1999/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.19991201-19991231.41W_9S_34W_7S.tif')

#2000
JAN_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000101-20000131.41W_9S_34W_7S.tif')
FEV_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000201-20000229.41W_9S_34W_7S.tif')
MAR_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000301-20000331.41W_9S_34W_7S.tif')
ABR_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000401-20000430.41W_9S_34W_7S.tif')
MAI_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000501-20000531.41W_9S_34W_7S.tif')
JUN_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000601-20000630.41W_9S_34W_7S.tif')
JUL_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000701-20000731.41W_9S_34W_7S.tif')
AGO_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000801-20000831.41W_9S_34W_7S.tif')
SET_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20000901-20000930.41W_9S_34W_7S.tif')
OUT_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20001001-20001031.41W_9S_34W_7S.tif')
NOV_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20001101-20001130.41W_9S_34W_7S.tif')
DEZ_2000 = rasterio.open('/content/drive/My Drive/TRMM/2000/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20001201-20001231.41W_9S_34W_7S.tif')

#2001
JAN_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010101-20010131.41W_9S_34W_7S.tif')
FEV_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010201-20010228.41W_9S_34W_7S.tif')
MAR_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010301-20010331.41W_9S_34W_7S.tif')
ABR_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010401-20010430.41W_9S_34W_7S.tif')
MAI_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010501-20010531.41W_9S_34W_7S.tif')
JUN_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010601-20010630.41W_9S_34W_7S.tif')
JUL_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010701-20010731.41W_9S_34W_7S.tif')
AGO_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010801-20010831.41W_9S_34W_7S.tif')
SET_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20010901-20010930.41W_9S_34W_7S.tif')
OUT_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20011001-20011031.41W_9S_34W_7S.tif')
NOV_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20011101-20011130.41W_9S_34W_7S.tif')
DEZ_2001 = rasterio.open('/content/drive/My Drive/TRMM/2001/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20011201-20011231.41W_9S_34W_7S.tif')

#2002
JAN_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020101-20020131.41W_9S_34W_7S.tif')
FEV_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020201-20020228.41W_9S_34W_7S.tif')
MAR_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020301-20020331.41W_9S_34W_7S.tif')
ABR_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020401-20020430.41W_9S_34W_7S.tif')
MAI_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020501-20020531.41W_9S_34W_7S.tif')
JUN_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020601-20020630.41W_9S_34W_7S.tif')
JUL_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020701-20020731.41W_9S_34W_7S.tif')
AGO_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020801-20020831.41W_9S_34W_7S.tif')
SET_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20020901-20020930.41W_9S_34W_7S.tif')
OUT_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20021001-20021031.41W_9S_34W_7S.tif')
NOV_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20021101-20021130.41W_9S_34W_7S.tif')
DEZ_2002 = rasterio.open('/content/drive/My Drive/TRMM/2002/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20021201-20021231.41W_9S_34W_7S.tif')

#2003
JAN_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20030101-20030131.41W_9S_34W_7S.tif')
FEV_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20030201-20030228.41W_9S_34W_7S.tif')
MAR_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20030301-20030331.41W_9S_34W_7S.tif')
ABR_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20030401-20030430.41W_9S_34W_7S.tif')
MAI_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20030501-20030531.41W_9S_34W_7S.tif')
JUN_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20030601-20030630.41W_9S_34W_7S.tif')
JUL_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-accumulate.TRMM_3B43_7_precipitation.20030701-20030731.41W_9S_34W_7S.tif')
AGO_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20030801-20030831.41W_9S_34W_7S.tif')
SET_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20030901-20030930.41W_9S_34W_7S.tif')
OUT_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20031001-20031031.41W_9S_34W_7S.tif')
NOV_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20031101-20031130.41W_9S_34W_7S.tif')
DEZ_2003 = rasterio.open('/content/drive/My Drive/TRMM/2003/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20031201-20031231.41W_9S_34W_7S.tif')

#2004
JAN_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-accumulate.TRMM_3B43_7_precipitation.20040101-20040131.41W_9S_34W_7S.tif')
FEV_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20040201-20040229.41W_9S_34W_7S.tif')
MAR_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20040301-20040331.41W_9S_34W_7S.tif')
ABR_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20040401-20040430.41W_9S_34W_7S.tif')
MAI_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-accumulate.TRMM_3B43_7_precipitation.20040501-20040531.41W_9S_34W_7S.tif')
JUN_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20040601-20040630.41W_9S_34W_7S.tif')
JUL_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20040701-20040731.41W_9S_34W_7S.tif')
AGO_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20040801-20040831.41W_9S_34W_7S.tif')
SET_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20040901-20040930.41W_9S_34W_7S.tif')
OUT_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20041001-20041031.41W_9S_34W_7S.tif')
NOV_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20041101-20041130.41W_9S_34W_7S.tif')
DEZ_2004 = rasterio.open('/content/drive/My Drive/TRMM/2004/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20041201-20041231.41W_9S_34W_7S.tif')

#2005
JAN_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050101-20050131.41W_9S_34W_7S.tif')
FEV_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050201-20050228.41W_9S_34W_7S.tif')
MAR_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050301-20050331.41W_9S_34W_7S.tif')
ABR_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050401-20050430.41W_9S_34W_7S.tif')
MAI_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050501-20050531.41W_9S_34W_7S.tif')
JUN_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050601-20050630.41W_9S_34W_7S.tif')
JUL_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050701-20050731.41W_9S_34W_7S.tif')
AGO_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050801-20050831.41W_9S_34W_7S.tif')
SET_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20050901-20050930.41W_9S_34W_7S.tif')
OUT_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20051001-20051031.41W_9S_34W_7S.tif')
NOV_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20051101-20051130.41W_9S_34W_7S.tif')
DEZ_2005 = rasterio.open('/content/drive/My Drive/TRMM/2005/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20051201-20051231.41W_9S_34W_7S.tif')

#2006
JAN_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060101-20060131.41W_9S_34W_7S.tif')
FEV_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060201-20060228.41W_9S_34W_7S.tif')
MAR_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060301-20060331.41W_9S_34W_7S.tif')
ABR_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060401-20060430.41W_9S_34W_7S.tif')
MAI_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060501-20060531.41W_9S_34W_7S.tif')
JUN_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060601-20060630.41W_9S_34W_7S.tif')
JUL_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060701-20060731.41W_9S_34W_7S.tif')
AGO_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060801-20060831.41W_9S_34W_7S.tif')
SET_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20060901-20060930.41W_9S_34W_7S.tif')
OUT_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20061001-20061031.41W_9S_34W_7S.tif')
NOV_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-accumulate.TRMM_3B43_7_precipitation.20061101-20061130.41W_9S_34W_7S.tif')
DEZ_2006 = rasterio.open('/content/drive/My Drive/TRMM/2006/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20061201-20061231.41W_9S_34W_7S.tif')

#2007
JAN_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070101-20070131.41W_9S_34W_7S.tif')
FEV_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070201-20070228.41W_9S_34W_7S.tif')
MAR_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070301-20070331.41W_9S_34W_7S.tif')
ABR_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070401-20070430.41W_9S_34W_7S.tif')
MAI_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070501-20070531.41W_9S_34W_7S.tif')
JUN_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070601-20070630.41W_9S_34W_7S.tif')
JUL_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070701-20070731.41W_9S_34W_7S.tif')
AGO_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070801-20070831.41W_9S_34W_7S.tif')
SET_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20070901-20070930.41W_9S_34W_7S.tif')
OUT_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20071001-20071031.41W_9S_34W_7S.tif')
NOV_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20071101-20071130.41W_9S_34W_7S.tif')
DEZ_2007 = rasterio.open('/content/drive/My Drive/TRMM/2007/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20071201-20071231.41W_9S_34W_7S.tif')

#2008
JAN_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080101-20080131.41W_9S_34W_7S.tif')
FEV_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080201-20080229.41W_9S_34W_7S.tif')
MAR_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080301-20080331.41W_9S_34W_7S.tif')
ABR_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080401-20080430.41W_9S_34W_7S.tif')
MAI_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080501-20080531.41W_9S_34W_7S.tif')
JUN_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080601-20080630.41W_9S_34W_7S.tif')
JUL_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080701-20080731.41W_9S_34W_7S.tif')
AGO_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080801-20080831.41W_9S_34W_7S.tif')
SET_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20080901-20080930.41W_9S_34W_7S.tif')
OUT_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20081001-20081031.41W_9S_34W_7S.tif')
NOV_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20081101-20081130.41W_9S_34W_7S.tif')
DEZ_2008 = rasterio.open('/content/drive/My Drive/TRMM/2008/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20081201-20081231.41W_9S_34W_7S.tif')

#2009
JAN_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090101-20090131.41W_9S_34W_7S.tif')
FEV_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090201-20090228.41W_9S_34W_7S.tif')
MAR_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090301-20090331.41W_9S_34W_7S.tif')
ABR_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090401-20090430.41W_9S_34W_7S.tif')
MAI_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090501-20090531.41W_9S_34W_7S.tif')
JUN_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090601-20090630.41W_9S_34W_7S.tif')
JUL_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090701-20090731.41W_9S_34W_7S.tif')
AGO_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090801-20090831.41W_9S_34W_7S.tif')
SET_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20090901-20090930.41W_9S_34W_7S.tif')
OUT_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20091001-20091031.41W_9S_34W_7S.tif')
NOV_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20091101-20091130.41W_9S_34W_7S.tif')
DEZ_2009 = rasterio.open('/content/drive/My Drive/TRMM/2009/GIOVANNI-g4.accumulate.TRMM_3B43_7_precipitation.20091201-20091231.41W_9S_34W_7S.tif')

 #2010
JAN_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/JAN_2010.tif')
FEV_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/FEV_2010.tif')
MAR_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/MAR_2010.tif')
ABR_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/ABR_2010.tif')
MAI_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/MAI_2010.tif')
JUN_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/JUN_2010.tif')
JUL_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/JUL_2010.tif')
AGO_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/AGO_2010.tif')
SET_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/SET_2010.tif')
OUT_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/OUT_2010.tif')
NOV_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/NOV_2010.tif')
DEZ_2010 = rasterio.open('/content/drive/My Drive/TRMM/2010/DEZ_2010.tif')

 #2011
JAN_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/JAN_2011.tif')
FEV_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/FEV_2011.tif')
MAR_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/MAR_2011.tif')
ABR_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/ABR_2011.tif')
MAI_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/MAI_2011.tif')
JUN_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/JUN_2011.tif')
JUL_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/JUL_2011.tif')
AGO_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/AGO_2011.tif')
SET_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/SET_2011.tif')
OUT_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/OUT_2011.tif')
NOV_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/NOV_2011.tif')
DEZ_2011 = rasterio.open('/content/drive/My Drive/TRMM/2011/DEZ_2011.tif')

 #2012
JAN_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/JAN_2012.tif')
FEV_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/FEV_2012.tif')
MAR_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/MAR_2012.tif')
ABR_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/ABR_2012.tif')
MAI_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/MAI_2012.tif')
JUN_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/JUN_2012.tif')
JUL_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/JUL_2012.tif')
AGO_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/AGO_2012.tif')
SET_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/SET_2012.tif')
OUT_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/OUT_2012.tif')
NOV_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/NOV_2012.tif')
DEZ_2012 = rasterio.open('/content/drive/My Drive/TRMM/2012/DEZ_2012.tif')

 #2013
JAN_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/JAN_2013.tif')
FEV_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/FEV_2013.tif')
MAR_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/MAR_2013.tif')
ABR_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/ABR_2013.tif')
MAI_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/MAI_2013.tif')
JUN_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/JUN_2013.tif')
JUL_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/JUL_2013.tif')
AGO_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/AGO_2013.tif')
SET_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/SET_2013.tif')
OUT_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/OUT_2013.tif')
NOV_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/NOV_2013.tif')
DEZ_2013 = rasterio.open('/content/drive/My Drive/TRMM/2013/DEZ_2013.tif')

 #2014
JAN_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/JAN_2014.tif')
FEV_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/FEV_2014.tif')
MAR_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/MAR_2014.tif')
ABR_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/ABR_2014.tif')
MAI_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/MAI_2014.tif')
JUN_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/JUN_2014.tif')
JUL_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/JUL_2014.tif')
AGO_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/AGO_2014.tif')
SET_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/SET_2014.tif')
OUT_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/OUT_2014.tif')
NOV_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/NOV_2014.tif')
DEZ_2014 = rasterio.open('/content/drive/My Drive/GPM/2014/DEZ_2014.tif')

 #2015
JAN_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/JAN_2015.tif')
FEV_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/FEV_2015.tif')
MAR_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/MAR_2015.tif')
ABR_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/ABR_2015.tif')
MAI_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/MAI_2015.tif')
JUN_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/JUN_2015.tif')
JUL_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/JUL_2015.tif')
AGO_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/AGO_2015.tif')
SET_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/SET_2015.tif')
OUT_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/OUT_2015.tif')
NOV_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/NOV_2015.tif')
DEZ_2015 = rasterio.open('/content/drive/My Drive/GPM/2015/DEZ_2015.tif')

 #2016
JAN_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/JAN_2016.tif')
FEV_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/FEV_2016.tif')
MAR_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/MAR_2016.tif')
ABR_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/ABR_2016.tif')
MAI_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/MAI_2016.tif')
JUN_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/JUN_2016.tif')
JUL_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/JUL_2016.tif')
AGO_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/AGO_2016.tif')
SET_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/SET_2016.tif')
OUT_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/OUT_2016.tif')
NOV_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/NOV_2016.tif')
DEZ_2016 = rasterio.open('/content/drive/My Drive/GPM/2016/DEZ_2016.tif')

 #2017
JAN_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/JAN_2017.tif')
FEV_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/FEV_2017.tif')
MAR_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/MAR_2017.tif')
ABR_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/ABR_2017.tif')
MAI_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/MAI_2017.tif')
JUN_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/JUN_2017.tif')
JUL_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/JUL_2017.tif')
AGO_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/AGO_2017.tif')
SET_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/SET_2017.tif')
OUT_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/OUT_2017.tif')
NOV_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/NOV_2017.tif')
DEZ_2017 = rasterio.open('/content/drive/My Drive/GPM/2017/DEZ_2017.tif')

 #2018
JAN_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/JAN_2018.tif')
FEV_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/FEV_2018.tif')
MAR_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/MAR_2018.tif')
ABR_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/ABR_2018.tif')
MAI_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/MAI_2018.tif')
JUN_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/JUN_2018.tif')
JUL_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/JUL_2018.tif')
AGO_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/AGO_2018.tif')
SET_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/SET_2018.tif')
OUT_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/OUT_2018.tif')
NOV_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/NOV_2018.tif')
DEZ_2018 = rasterio.open('/content/drive/My Drive/GPM/2018/DEZ_2018.tif')

 #2019
JAN_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/JAN_2019.tif')
FEV_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/FEV_2019.tif')
MAR_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/MAR_2019.tif')
ABR_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/ABR_2019.tif')
MAI_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/MAI_2019.tif')
JUN_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/JUN_2019.tif')
JUL_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/JUL_2019.tif')
AGO_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/AGO_2019.tif')
SET_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/SET_2019.tif')
OUT_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/OUT_2019.tif')
NOV_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/NOV_2019.tif')
DEZ_2019 = rasterio.open('/content/drive/My Drive/GPM/2019/DEZ_2019.tif')

#2020
JAN_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20200101-20200131.41W_9S_34W_7S.tif')
FEV_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-accumulate.GPM_3IMERGM_06_precipitation.20200201-20200229.41W_9S_34W_7S.tif')
MAR_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-accumulate.GPM_3IMERGM_06_precipitation.20200301-20200331.41W_9S_34W_7S.tif')
ABR_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20200401-20200430.41W_9S_34W_7S.tif')
MAI_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20200501-20200531.41W_9S_34W_7S.tif')
JUN_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20200601-20200630.41W_9S_34W_7S.tif')
JUL_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20200701-20200731.41W_9S_34W_7S.tif')
AGO_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20200801-20200831.41W_9S_34W_7S.tif')
SET_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20200901-20200930.41W_9S_34W_7S.tif')
OUT_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20201001-20201031.41W_9S_34W_7S.tif')
NOV_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20201101-20201130.41W_9S_34W_7S.tif')
DEZ_2020 = rasterio.open('/content/drive/My Drive/GPM/2020/GIOVANNI-g4.accumulate.GPM_3IMERGM_06_precipitation.20201201-20201231.41W_9S_34W_7S.tif')

# Read points from shapefile
'''pts = gpd.read_file('estacoes_precipitaca.shp')
pts'''

pts = gpd.read_file('estacoes_precipitaca.shp')
pts.columns.tolist()



def extrairPixel_(imagem,arquivoDeCoordenadas,mes,ano):
  # Read points from shapefile
  #arquivoDeCoordenadas = gdfCoordenadas[(gdfCoordenadas['CODIGO']==codigo)
  
  arquivoDeCoordenadas = arquivoDeCoordenadas[pts.columns.tolist()]
  arquivoDeCoordenadas.index = range(len(arquivoDeCoordenadas))
  coords = [(x,y) for x, y in zip(arquivoDeCoordenadas.LONG, arquivoDeCoordenadas.LAT)]
  arquivoDeCoordenadas['MES'] = mes
  arquivoDeCoordenadas['ANO'] = ano
  arquivoDeCoordenadas['PRECIPITACAO'] = [x[0] for x in imagem.sample(coords)]
  arquivoDeCoordenadas=pd.DataFrame(arquivoDeCoordenadas)
  return arquivoDeCoordenadas



JAN_1998__=extrairPixel_(JAN_1998,pts,1,1998)
print(JAN_1998__)

# 1998
JAN_1998__=extrairPixel_(JAN_1998,pts,1,1998)
FEV_1998__=extrairPixel_(FEV_1998,pts,2,1998)
MAR_1998__=extrairPixel_(MAR_1998,pts,3,1998)
ABR_1998__=extrairPixel_(ABR_1998,pts,4,1998)
MAI_1998__=extrairPixel_(MAI_1998,pts,5,1998)
JUN_1998__=extrairPixel_(JUN_1998,pts,6,1998)
JUL_1998__=extrairPixel_(JUL_1998,pts,7,1998)
AGO_1998__=extrairPixel_(AGO_1998,pts,8,1998)
SET_1998__=extrairPixel_(SET_1998,pts,9,1998)
OUT_1998__=extrairPixel_(OUT_1998,pts,10,1998)
NOV_1998__=extrairPixel_(NOV_1998,pts,11,1998)
DEZ_1998__=extrairPixel_(DEZ_1998,pts,12,1998)

# 1999
JAN_1999__=extrairPixel_(JAN_1999,pts,1,1999)
FEV_1999__=extrairPixel_(FEV_1999,pts,2,1999)
MAR_1999__=extrairPixel_(MAR_1999,pts,3,1999)
ABR_1999__=extrairPixel_(ABR_1999,pts,4,1999)
MAI_1999__=extrairPixel_(MAI_1999,pts,5,1999)
JUN_1999__=extrairPixel_(JUN_1999,pts,6,1999)
JUL_1999__=extrairPixel_(JUL_1999,pts,7,1999)
AGO_1999__=extrairPixel_(AGO_1999,pts,8,1999)
SET_1999__=extrairPixel_(SET_1999,pts,9,1999)
OUT_1999__=extrairPixel_(OUT_1999,pts,10,1999)
NOV_1999__=extrairPixel_(NOV_1999,pts,11,1999)
DEZ_1999__=extrairPixel_(DEZ_1999,pts,12,1999)

# 2000
JAN_2000__=extrairPixel_(JAN_2000,pts,1,2000)
FEV_2000__=extrairPixel_(FEV_2000,pts,2,2000)
MAR_2000__=extrairPixel_(MAR_2000,pts,3,2000)
ABR_2000__=extrairPixel_(ABR_2000,pts,4,2000)
MAI_2000__=extrairPixel_(MAI_2000,pts,5,2000)
JUN_2000__=extrairPixel_(JUN_2000,pts,6,2000)
JUL_2000__=extrairPixel_(JUL_2000,pts,7,2000)
AGO_2000__=extrairPixel_(AGO_2000,pts,8,2000)
SET_2000__=extrairPixel_(SET_2000,pts,9,2000)
OUT_2000__=extrairPixel_(OUT_2000,pts,10,2000)
NOV_2000__=extrairPixel_(NOV_2000,pts,11,2000)
DEZ_2000__=extrairPixel_(DEZ_2000,pts,12,2000)

# 2001
JAN_2001__=extrairPixel_(JAN_2001,pts,1,2001)
FEV_2001__=extrairPixel_(FEV_2001,pts,2,2001)
MAR_2001__=extrairPixel_(MAR_2001,pts,3,2001)
ABR_2001__=extrairPixel_(ABR_2001,pts,4,2001)
MAI_2001__=extrairPixel_(MAI_2001,pts,5,2001)
JUN_2001__=extrairPixel_(JUN_2001,pts,6,2001)
JUL_2001__=extrairPixel_(JUL_2001,pts,7,2001)
AGO_2001__=extrairPixel_(AGO_2001,pts,8,2001)
SET_2001__=extrairPixel_(SET_2001,pts,9,2001)
OUT_2001__=extrairPixel_(OUT_2001,pts,10,2001)
NOV_2001__=extrairPixel_(NOV_2001,pts,11,2001)
DEZ_2001__=extrairPixel_(DEZ_2001,pts,12,2001)

# 2002
JAN_2002__=extrairPixel_(JAN_2002,pts,1,2002)
FEV_2002__=extrairPixel_(FEV_2002,pts,2,2002)
MAR_2002__=extrairPixel_(MAR_2002,pts,3,2002)
ABR_2002__=extrairPixel_(ABR_2002,pts,4,2002)
MAI_2002__=extrairPixel_(MAI_2002,pts,5,2002)
JUN_2002__=extrairPixel_(JUN_2002,pts,6,2002)
JUL_2002__=extrairPixel_(JUL_2002,pts,7,2002)
AGO_2002__=extrairPixel_(AGO_2002,pts,8,2002)
SET_2002__=extrairPixel_(SET_2002,pts,9,2002)
OUT_2002__=extrairPixel_(OUT_2002,pts,10,2002)
NOV_2002__=extrairPixel_(NOV_2002,pts,11,2002)
DEZ_2002__=extrairPixel_(DEZ_2002,pts,12,2002)

# 2003
JAN_2003__=extrairPixel_(JAN_2003,pts,1,2003)
FEV_2003__=extrairPixel_(FEV_2003,pts,2,2003)
MAR_2003__=extrairPixel_(MAR_2003,pts,3,2003)
ABR_2003__=extrairPixel_(ABR_2003,pts,4,2003)
MAI_2003__=extrairPixel_(MAI_2003,pts,5,2003)
JUN_2003__=extrairPixel_(JUN_2003,pts,6,2003)
JUL_2003__=extrairPixel_(JUL_2003,pts,7,2003)
AGO_2003__=extrairPixel_(AGO_2003,pts,8,2003)
SET_2003__=extrairPixel_(SET_2003,pts,9,2003)
OUT_2003__=extrairPixel_(OUT_2003,pts,10,2003)
NOV_2003__=extrairPixel_(NOV_2003,pts,11,2003)
DEZ_2003__=extrairPixel_(DEZ_2003,pts,12,2003)

# 2004
JAN_2004__=extrairPixel_(JAN_2004,pts,1,2004)
FEV_2004__=extrairPixel_(FEV_2004,pts,2,2004)
MAR_2004__=extrairPixel_(MAR_2004,pts,3,2004)
ABR_2004__=extrairPixel_(ABR_2004,pts,4,2004)
MAI_2004__=extrairPixel_(MAI_2004,pts,5,2004)
JUN_2004__=extrairPixel_(JUN_2004,pts,6,2004)
JUL_2004__=extrairPixel_(JUL_2004,pts,7,2004)
AGO_2004__=extrairPixel_(AGO_2004,pts,8,2004)
SET_2004__=extrairPixel_(SET_2004,pts,9,2004)
OUT_2004__=extrairPixel_(OUT_2004,pts,10,2004)
NOV_2004__=extrairPixel_(NOV_2004,pts,11,2004)
DEZ_2004__=extrairPixel_(DEZ_2004,pts,12,2004)

# 2005
JAN_2005__=extrairPixel_(JAN_2005,pts,1,2005)
FEV_2005__=extrairPixel_(FEV_2005,pts,2,2005)
MAR_2005__=extrairPixel_(MAR_2005,pts,3,2005)
ABR_2005__=extrairPixel_(ABR_2005,pts,4,2005)
MAI_2005__=extrairPixel_(MAI_2005,pts,5,2005)
JUN_2005__=extrairPixel_(JUN_2005,pts,6,2005)
JUL_2005__=extrairPixel_(JUL_2005,pts,7,2005)
AGO_2005__=extrairPixel_(AGO_2005,pts,8,2005)
SET_2005__=extrairPixel_(SET_2005,pts,9,2005)
OUT_2005__=extrairPixel_(OUT_2005,pts,10,2005)
NOV_2005__=extrairPixel_(NOV_2005,pts,11,2005)
DEZ_2005__=extrairPixel_(DEZ_2005,pts,12,2005)

# 2006
JAN_2006__=extrairPixel_(JAN_2006,pts,1,2006)
FEV_2006__=extrairPixel_(FEV_2006,pts,2,2006)
MAR_2006__=extrairPixel_(MAR_2006,pts,3,2006)
ABR_2006__=extrairPixel_(ABR_2006,pts,4,2006)
MAI_2006__=extrairPixel_(MAI_2006,pts,5,2006)
JUN_2006__=extrairPixel_(JUN_2006,pts,6,2006)
JUL_2006__=extrairPixel_(JUL_2006,pts,7,2006)
AGO_2006__=extrairPixel_(AGO_2006,pts,8,2006)
SET_2006__=extrairPixel_(SET_2006,pts,9,2006)
OUT_2006__=extrairPixel_(OUT_2006,pts,10,2006)
NOV_2006__=extrairPixel_(NOV_2006,pts,11,2006)
DEZ_2006__=extrairPixel_(DEZ_2006,pts,12,2006)

# 2007
JAN_2007__=extrairPixel_(JAN_2007,pts,1,2007)
FEV_2007__=extrairPixel_(FEV_2007,pts,2,2007)
MAR_2007__=extrairPixel_(MAR_2007,pts,3,2007)
ABR_2007__=extrairPixel_(ABR_2007,pts,4,2007)
MAI_2007__=extrairPixel_(MAI_2007,pts,5,2007)
JUN_2007__=extrairPixel_(JUN_2007,pts,6,2007)
JUL_2007__=extrairPixel_(JUL_2007,pts,7,2007)
AGO_2007__=extrairPixel_(AGO_2007,pts,8,2007)
SET_2007__=extrairPixel_(SET_2007,pts,9,2007)
OUT_2007__=extrairPixel_(OUT_2007,pts,10,2007)
NOV_2007__=extrairPixel_(NOV_2007,pts,11,2007)
DEZ_2007__=extrairPixel_(DEZ_2007,pts,12,2007)

# 2008
JAN_2008__=extrairPixel_(JAN_2008,pts,1,2008)
FEV_2008__=extrairPixel_(FEV_2008,pts,2,2008)
MAR_2008__=extrairPixel_(MAR_2008,pts,3,2008)
ABR_2008__=extrairPixel_(ABR_2008,pts,4,2008)
MAI_2008__=extrairPixel_(MAI_2008,pts,5,2008)
JUN_2008__=extrairPixel_(JUN_2008,pts,6,2008)
JUL_2008__=extrairPixel_(JUL_2008,pts,7,2008)
AGO_2008__=extrairPixel_(AGO_2008,pts,8,2008)
SET_2008__=extrairPixel_(SET_2008,pts,9,2008)
OUT_2008__=extrairPixel_(OUT_2008,pts,10,2008)
NOV_2008__=extrairPixel_(NOV_2008,pts,11,2008)
DEZ_2008__=extrairPixel_(DEZ_2008,pts,12,2008)

# 2009
JAN_2009__=extrairPixel_(JAN_2009,pts,1,2009)
FEV_2009__=extrairPixel_(FEV_2009,pts,2,2009)
MAR_2009__=extrairPixel_(MAR_2009,pts,3,2009)
ABR_2009__=extrairPixel_(ABR_2009,pts,4,2009)
MAI_2009__=extrairPixel_(MAI_2009,pts,5,2009)
JUN_2009__=extrairPixel_(JUN_2009,pts,6,2009)
JUL_2009__=extrairPixel_(JUL_2009,pts,7,2009)
AGO_2009__=extrairPixel_(AGO_2009,pts,8,2009)
SET_2009__=extrairPixel_(SET_2009,pts,9,2009)
OUT_2009__=extrairPixel_(OUT_2009,pts,10,2009)
NOV_2009__=extrairPixel_(NOV_2009,pts,11,2009)
DEZ_2009__=extrairPixel_(DEZ_2009,pts,12,2009)

# 2010
JAN_2010__=extrairPixel_(JAN_2010,pts,1,2010)
FEV_2010__=extrairPixel_(FEV_2010,pts,2,2010)
MAR_2010__=extrairPixel_(MAR_2010,pts,3,2010)
ABR_2010__=extrairPixel_(ABR_2010,pts,4,2010)
MAI_2010__=extrairPixel_(MAI_2010,pts,5,2010)
JUN_2010__=extrairPixel_(JUN_2010,pts,6,2010)
JUL_2010__=extrairPixel_(JUL_2010,pts,7,2010)
AGO_2010__=extrairPixel_(AGO_2010,pts,8,2010)
SET_2010__=extrairPixel_(SET_2010,pts,9,2010)
OUT_2010__=extrairPixel_(OUT_2010,pts,10,2010)
NOV_2010__=extrairPixel_(NOV_2010,pts,11,2010)
DEZ_2010__=extrairPixel_(DEZ_2010,pts,12,2010)

# 2011
JAN_2011__=extrairPixel_(JAN_2011,pts,1,2011)
FEV_2011__=extrairPixel_(FEV_2011,pts,2,2011)
MAR_2011__=extrairPixel_(MAR_2011,pts,3,2011)
ABR_2011__=extrairPixel_(ABR_2011,pts,4,2011)
MAI_2011__=extrairPixel_(MAI_2011,pts,5,2011)
JUN_2011__=extrairPixel_(JUN_2011,pts,6,2011)
JUL_2011__=extrairPixel_(JUL_2011,pts,7,2011)
AGO_2011__=extrairPixel_(AGO_2011,pts,8,2011)
SET_2011__=extrairPixel_(SET_2011,pts,9,2011)
OUT_2011__=extrairPixel_(OUT_2011,pts,10,2011)
NOV_2011__=extrairPixel_(NOV_2011,pts,11,2011)
DEZ_2011__=extrairPixel_(DEZ_2011,pts,12,2011)

# 2012
JAN_2012__=extrairPixel_(JAN_2012,pts,1,2012)
FEV_2012__=extrairPixel_(FEV_2012,pts,2,2012)
MAR_2012__=extrairPixel_(MAR_2012,pts,3,2012)
ABR_2012__=extrairPixel_(ABR_2012,pts,4,2012)
MAI_2012__=extrairPixel_(MAI_2012,pts,5,2012)
JUN_2012__=extrairPixel_(JUN_2012,pts,6,2012)
JUL_2012__=extrairPixel_(JUL_2012,pts,7,2012)
AGO_2012__=extrairPixel_(AGO_2012,pts,8,2012)
SET_2012__=extrairPixel_(SET_2012,pts,9,2012)
OUT_2012__=extrairPixel_(OUT_2012,pts,10,2012)
NOV_2012__=extrairPixel_(NOV_2012,pts,11,2012)
DEZ_2012__=extrairPixel_(DEZ_2012,pts,12,2012)

# 2013
JAN_2013__=extrairPixel_(JAN_2013,pts,1,2013)
FEV_2013__=extrairPixel_(FEV_2013,pts,2,2013)
MAR_2013__=extrairPixel_(MAR_2013,pts,3,2013)
ABR_2013__=extrairPixel_(ABR_2013,pts,4,2013)
MAI_2013__=extrairPixel_(MAI_2013,pts,5,2013)
JUN_2013__=extrairPixel_(JUN_2013,pts,6,2013)
JUL_2013__=extrairPixel_(JUL_2013,pts,7,2013)
AGO_2013__=extrairPixel_(AGO_2013,pts,8,2013)
SET_2013__=extrairPixel_(SET_2013,pts,9,2013)
OUT_2013__=extrairPixel_(OUT_2013,pts,10,2013)
NOV_2013__=extrairPixel_(NOV_2013,pts,11,2013)
DEZ_2013__=extrairPixel_(DEZ_2013,pts,12,2013)

# 2014
JAN_2014__=extrairPixel_(JAN_2014,pts,1,2014)
FEV_2014__=extrairPixel_(FEV_2014,pts,2,2014)
MAR_2014__=extrairPixel_(MAR_2014,pts,3,2014)
ABR_2014__=extrairPixel_(ABR_2014,pts,4,2014)
MAI_2014__=extrairPixel_(MAI_2014,pts,5,2014)
JUN_2014__=extrairPixel_(JUN_2014,pts,6,2014)
JUL_2014__=extrairPixel_(JUL_2014,pts,7,2014)
AGO_2014__=extrairPixel_(AGO_2014,pts,8,2014)
SET_2014__=extrairPixel_(SET_2014,pts,9,2014)
OUT_2014__=extrairPixel_(OUT_2014,pts,10,2014)
NOV_2014__=extrairPixel_(NOV_2014,pts,11,2014)
DEZ_2014__=extrairPixel_(DEZ_2014,pts,12,2014)

# 2015
JAN_2015__=extrairPixel_(JAN_2015,pts,1,2015)
FEV_2015__=extrairPixel_(FEV_2015,pts,2,2015)
MAR_2015__=extrairPixel_(MAR_2015,pts,3,2015)
ABR_2015__=extrairPixel_(ABR_2015,pts,4,2015)
MAI_2015__=extrairPixel_(MAI_2015,pts,5,2015)
JUN_2015__=extrairPixel_(JUN_2015,pts,6,2015)
JUL_2015__=extrairPixel_(JUL_2015,pts,7,2015)
AGO_2015__=extrairPixel_(AGO_2015,pts,8,2015)
SET_2015__=extrairPixel_(SET_2015,pts,9,2015)
OUT_2015__=extrairPixel_(OUT_2015,pts,10,2015)
NOV_2015__=extrairPixel_(NOV_2015,pts,11,2015)
DEZ_2015__=extrairPixel_(DEZ_2015,pts,12,2015)

# 2016
JAN_2016__=extrairPixel_(JAN_2016,pts,1,2016)
FEV_2016__=extrairPixel_(FEV_2016,pts,2,2016)
MAR_2016__=extrairPixel_(MAR_2016,pts,3,2016)
ABR_2016__=extrairPixel_(ABR_2016,pts,4,2016)
MAI_2016__=extrairPixel_(MAI_2016,pts,5,2016)
JUN_2016__=extrairPixel_(JUN_2016,pts,6,2016)
JUL_2016__=extrairPixel_(JUL_2016,pts,7,2016)
AGO_2016__=extrairPixel_(AGO_2016,pts,8,2016)
SET_2016__=extrairPixel_(SET_2016,pts,9,2016)
OUT_2016__=extrairPixel_(OUT_2016,pts,10,2016)
NOV_2016__=extrairPixel_(NOV_2016,pts,11,2016)
DEZ_2016__=extrairPixel_(DEZ_2016,pts,12,2016)

# 2017
JAN_2017__=extrairPixel_(JAN_2017,pts,1,2017)
FEV_2017__=extrairPixel_(FEV_2017,pts,2,2017)
MAR_2017__=extrairPixel_(MAR_2017,pts,3,2017)
ABR_2017__=extrairPixel_(ABR_2017,pts,4,2017)
MAI_2017__=extrairPixel_(MAI_2017,pts,5,2017)
JUN_2017__=extrairPixel_(JUN_2017,pts,6,2017)
JUL_2017__=extrairPixel_(JUL_2017,pts,7,2017)
AGO_2017__=extrairPixel_(AGO_2017,pts,8,2017)
SET_2017__=extrairPixel_(SET_2017,pts,9,2017)
OUT_2017__=extrairPixel_(OUT_2017,pts,10,2017)
NOV_2017__=extrairPixel_(NOV_2017,pts,11,2017)
DEZ_2017__=extrairPixel_(DEZ_2017,pts,12,2017)

# 2018
JAN_2018__=extrairPixel_(JAN_2018,pts,1,2018)
FEV_2018__=extrairPixel_(FEV_2018,pts,2,2018)
MAR_2018__=extrairPixel_(MAR_2018,pts,3,2018)
ABR_2018__=extrairPixel_(ABR_2018,pts,4,2018)
MAI_2018__=extrairPixel_(MAI_2018,pts,5,2018)
JUN_2018__=extrairPixel_(JUN_2018,pts,6,2018)
JUL_2018__=extrairPixel_(JUL_2018,pts,7,2018)
AGO_2018__=extrairPixel_(AGO_2018,pts,8,2018)
SET_2018__=extrairPixel_(SET_2018,pts,9,2018)
OUT_2018__=extrairPixel_(OUT_2018,pts,10,2018)
NOV_2018__=extrairPixel_(NOV_2018,pts,11,2018)
DEZ_2018__=extrairPixel_(DEZ_2018,pts,12,2018)

# 2019
JAN_2019__=extrairPixel_(JAN_2019,pts,1,2019)
FEV_2019__=extrairPixel_(FEV_2019,pts,2,2019)
MAR_2019__=extrairPixel_(MAR_2019,pts,3,2019)
ABR_2019__=extrairPixel_(ABR_2019,pts,4,2019)
MAI_2019__=extrairPixel_(MAI_2019,pts,5,2019)
JUN_2019__=extrairPixel_(JUN_2019,pts,6,2019)
JUL_2019__=extrairPixel_(JUL_2019,pts,7,2019)
AGO_2019__=extrairPixel_(AGO_2019,pts,8,2019)
SET_2019__=extrairPixel_(SET_2019,pts,9,2019)
OUT_2019__=extrairPixel_(OUT_2019,pts,10,2019)
NOV_2019__=extrairPixel_(NOV_2019,pts,11,2019)
DEZ_2019__=extrairPixel_(DEZ_2019,pts,12,2019)

# 2020
JAN_2020__=extrairPixel_(JAN_2020,pts,1,2020)
FEV_2020__=extrairPixel_(FEV_2020,pts,2,2020)
MAR_2020__=extrairPixel_(MAR_2020,pts,3,2020)
ABR_2020__=extrairPixel_(ABR_2020,pts,4,2020)
MAI_2020__=extrairPixel_(MAI_2020,pts,5,2020)
JUN_2020__=extrairPixel_(JUN_2020,pts,6,2020)
JUL_2020__=extrairPixel_(JUL_2020,pts,7,2020)
AGO_2020__=extrairPixel_(AGO_2020,pts,8,2020)
SET_2020__=extrairPixel_(SET_2020,pts,9,2020)
OUT_2020__=extrairPixel_(OUT_2020,pts,10,2020)
NOV_2020__=extrairPixel_(NOV_2020,pts,11,2020)
DEZ_2020__=extrairPixel_(DEZ_2020,pts,12,2020)

BD=pd.concat([JAN_1998__,FEV_1998__,MAR_1998__,ABR_1998__,MAI_1998__,\
              JUN_1998__,JUL_1998__,AGO_1998__,SET_1998__,OUT_1998__,\
              NOV_1998__,DEZ_1998__,JAN_1999__,FEV_1999__,MAR_1999__,ABR_1999__,MAI_1999__,\
              JUN_1999__,JUL_1999__,AGO_1999__,SET_1999__,OUT_1999__,\
              NOV_1999__,DEZ_1999__,JAN_2000__,FEV_2000__,MAR_2000__,ABR_2000__,MAI_2000__,\
              JUN_2000__,JUL_2000__,AGO_2000__,SET_2000__,OUT_2000__,\
              NOV_2000__,DEZ_2000__,JAN_2001__,FEV_2001__,MAR_2001__,ABR_2001__,MAI_2001__,\
              JUN_2001__,JUL_2001__,AGO_2001__,SET_2001__,OUT_2001__,\
              NOV_2001__,DEZ_2001__,JAN_2002__,FEV_2002__,MAR_2002__,ABR_2002__,MAI_2002__,\
              JUN_2002__,JUL_2002__,AGO_2002__,SET_2002__,OUT_2002__,\
              NOV_2002__,DEZ_2002__,JAN_2003__,FEV_2003__,MAR_2003__,ABR_2003__,MAI_2003__,\
              JUN_2003__,JUL_2003__,AGO_2003__,SET_2003__,OUT_2003__,\
              NOV_2003__,DEZ_2003__,JAN_2004__,FEV_2004__,MAR_2004__,ABR_2004__,MAI_2004__,\
              JUN_2004__,JUL_2004__,AGO_2004__,SET_2004__,OUT_2004__,\
              NOV_2004__,DEZ_2004__,JAN_2005__,FEV_2005__,MAR_2005__,ABR_2005__,MAI_2005__,\
              JUN_2005__,JUL_2005__,AGO_2005__,SET_2005__,OUT_2005__,\
              NOV_2005__,DEZ_2005__,JAN_2006__,FEV_2006__,MAR_2006__,ABR_2006__,MAI_2006__,\
              JUN_2006__,JUL_2006__,AGO_2006__,SET_2006__,OUT_2006__,\
              NOV_2006__,DEZ_2006__,JAN_2007__,FEV_2007__,MAR_2007__,ABR_2007__,MAI_2007__,\
              JUN_2007__,JUL_2007__,AGO_2007__,SET_2007__,OUT_2007__,\
              NOV_2007__,DEZ_2007__,JAN_2008__,FEV_2008__,MAR_2008__,ABR_2008__,MAI_2008__,\
              JUN_2008__,JUL_2008__,AGO_2008__,SET_2008__,OUT_2008__,\
              NOV_2008__,DEZ_2008__,JAN_2009__,FEV_2009__,MAR_2009__,ABR_2009__,MAI_2009__,\
              JUN_2009__,JUL_2009__,AGO_2009__,SET_2009__,OUT_2009__,\
              NOV_2009__,DEZ_2009__,JAN_2010__,FEV_2010__,MAR_2010__,ABR_2010__,MAI_2010__,\
              JUN_2010__,JUL_2010__,AGO_2010__,SET_2010__,OUT_2010__,\
              NOV_2010__,DEZ_2010__,JAN_2011__,FEV_2011__,MAR_2011__,ABR_2011__,MAI_2011__,\
              JUN_2011__,JUL_2011__,AGO_2011__,SET_2011__,OUT_2011__,\
              NOV_2011__,DEZ_2011__,JAN_2012__,FEV_2012__,MAR_2012__,ABR_2012__,MAI_2012__,\
              JUN_2012__,JUL_2012__,AGO_2012__,SET_2012__,OUT_2012__,\
              NOV_2012__,DEZ_2012__,JAN_2013__,FEV_2013__,MAR_2013__,ABR_2013__,MAI_2013__,\
              JUN_2013__,JUL_2013__,AGO_2013__,SET_2013__,OUT_2013__,\
              NOV_2013__,DEZ_2013__,JAN_2014__,FEV_2014__,MAR_2014__,ABR_2014__,MAI_2014__,\
              JUN_2014__,JUL_2014__,AGO_2014__,SET_2014__,OUT_2014__,\
              NOV_2014__,DEZ_2014__,JAN_2015__,FEV_2015__,MAR_2015__,ABR_2015__,MAI_2015__,\
              JUN_2015__,JUL_2015__,AGO_2015__,SET_2015__,OUT_2015__,\
              NOV_2015__,DEZ_2015__,JAN_2016__,FEV_2016__,MAR_2016__,ABR_2016__,MAI_2016__,\
              JUN_2016__,JUL_2016__,AGO_2016__,SET_2016__,OUT_2016__,\
              NOV_2016__,DEZ_2016__,JAN_2017__,FEV_2017__,MAR_2017__,ABR_2017__,MAI_2017__,\
              JUN_2017__,JUL_2017__,AGO_2017__,SET_2017__,OUT_2017__,\
              NOV_2017__,DEZ_2017__,JAN_2018__,FEV_2018__,MAR_2018__,ABR_2018__,MAI_2018__,\
              JUN_2018__,JUL_2018__,AGO_2018__,SET_2018__,OUT_2018__,\
              NOV_2018__,DEZ_2018__,JAN_2019__,FEV_2019__,MAR_2019__,ABR_2019__,MAI_2019__,\
              JUN_2019__,JUL_2019__,AGO_2019__,SET_2019__,OUT_2019__,\
              NOV_2019__,DEZ_2019__,JAN_2020__,FEV_2020__,MAR_2020__,ABR_2020__,MAI_2020__,\
              JUN_2020__,JUL_2020__,AGO_2020__,SET_2020__,OUT_2020__,\
              NOV_2020__,DEZ_2020__])

# Exportar os dados 


from google.colab import drive
drive.mount ('/drive')
BD.to_csv('/drive/MyDrive/BD_1998_2020.csv')